apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  labels:
    app: go-app
spec:
  # this replica represent how many Pod you want to create
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      # Modify the container with yours
      containers:
      - name: golang-app
        image: yogas4/golang-app:{{ Values.image.tag }}
        ports:
        - containerPort: 8080