apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-go-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: "go-app.local" # This is your Domain web
    http:
      paths:
      - pathType: Prefix
        path: "/" # This is a Path In website
        backend:
          service:
            name: go-app # Change with your K8s Service
            port:
              number: 80