apiVersion: v1
kind: Service
metadata:
  name: go-app  # this name can be anything
spec:
  type: NodePort
  selector:
    app: go-app
  ports:
    - port: 80
      # Change the target Port which you're app is running.
      # because my app in docker using 8000
      targetPort: 8080
      nodePort: 30007